name: Build Android APK

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # --- THE BAIT ---
    - name: Load Java 17 (To appease the cloud server)
      uses: actions/setup-java@v4
      with:
        java-version: '17' 
        distribution: 'temurin'

    - name: Generate Legacy Gradle Engine
      run: gradle wrapper --gradle-version 7.4.2

    # --- THE SWITCH ---
    - name: Load Java 11 (To appease the Android code)
      uses: actions/setup-java@v4
      with:
        java-version: '11' 
        distribution: 'temurin'

    - name: Make Engine Executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UsbTerminal-Test-Build
        path: app/build/outputs/apk/debug/*.apk
